language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - bin/phpspec run;
  - if [ "$EXECUTE_CS_CHECK" == "true" ]; then bin/php-cs-fixer fix -v --diff --dry-run; fi
