language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - bin/phpspec run
